# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    
    - uses: aquiladev/ipfs-action@v0.1.1
      id: upload
      with:
        path: ./build
    
    - name: Update DNS Link via Cloudflare
      env:
        CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
        RECORD_DOMAIN: 'yungtesla.nl'
        RECORD_NAME: '_dnslink'
        CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        CID: 'QmSVQ5p1i5N8GXbquijYbiFAQw8N33nG39fmfi1bha8EWw'
      id: cloudflare-dnslink
      uses: ReSource-Network/cloudlfare-dnslink-update@v1.2
      with:
        cid: 'QmSVQ5p1i5N8GXbquijYbiFAQw8N33nG39fmfi1bha8EWw'

